spring:
  datasource:
    password: mypassword
    url: jdbc:mysql://localhost:3306/serverdb
    username: demo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true